# Generated by Django 4.0 on 2022-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_article_visitor_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='article-banner'),
        ),
    ]
