# Generated by Django 4.0 on 2022-10-27 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
