# Generated by Django 4.0 on 2022-11-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametag', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
    ]
